# Generated by Django 5.0.6 on 2024-07-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.IntegerField()),
                ('prix_unit_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unit_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_entree', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.IntegerField()),
                ('date_deplacement', models.DateField(auto_now_add=True)),
                ('chantier_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='deplacement.chantier')),
                ('chantier_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='deplacement.chantier')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deplacement.materiel')),
            ],
        ),
    ]
