# Generated by Django 5.0.6 on 2024-07-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='nom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Materiels', to='deplacement.chantier'),
            preserve_default=False,
        ),
    ]
