# Generated by Django 5.0.6 on 2024-07-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0002_materiel_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='nom',
            new_name='chantier',
        ),
    ]
