# Generated by Django 5.0.6 on 2024-07-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0003_rename_nom_materiel_chantier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='deplacement.chantier'),
        ),
    ]
