# Generated by Django 5.0.6 on 2024-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0005_alter_deplacement_date_deplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacement',
            name='date_deplacement',
            field=models.DateField(auto_now_add=True),
        ),
    ]
