# Generated by Django 5.0.6 on 2024-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0006_alter_deplacement_date_deplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacement',
            name='date_deplacement',
            field=models.DateField(),
        ),
    ]
